# Site settings
title: "Realjin Blog"
tagline : 리얼진블로그
description: "직장생활 하다 이런적 있죠? 누구나 한 번쯤은 직장생활을 하며 겪었을 이야기를 솔직하게 적어보았습니다. 이 많은 이야기들 중 하나는 공감하실 수 있을지도 몰라요! 리얼진블로그로 오세요!"
url: "https://realjin.co.kr"
author:
  name: "realjin"
  email: "iam@realjin.co.kr"
  url: "https://realjin.co.kr"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
permalink: pretty
paginate: 8

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# 블로그 disqus shortname
disqus:
  shortname: realjin
